version: '3.8'

services:
  app:
    image: golang:1.23.0-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "go mod download && go run cmd/shortener/main.go"
    environment:
      # - DATABASE_DSN=postgres://user:password@db:5432/workdb?sslmode=disable
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=workdb
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - db-data:/var/lib/repository/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: workdb
    ports:
      - "5432:5432"

volumes:
  db-data:
